elasticsearch:
  build: .
  dockerfile: Dockerfile.elasticsearch 
  command: elasticsearch -Des.network.host=0.0.0.0
  ports:
    - "9200:9200"
    - "9300:9300"
kibana:
  build: .
  dockerfile: Dockerfile.kibana 
  ports:
    - "5601:5601"
  links:
    - elasticsearch
spark:
  build: .
  dockerfile: Dockerfile.spark
  command: <consumer_key> <consumer_secret> <access_token> <access_token_secret> [<filters>]

  ports:
    - "4040:4040"
  links:
    - elasticsearch 
