elasticsearch:
  build: .
  dockerfile: Dockerfile.elasticsearch 
  command: elasticsearch -Des.network.host=0.0.0.0
  ports:
    - "9200:9200"
    - "9300:9300"
kibana:
  build: .
  dockerfile: Dockerfile.kibana 
  ports:
    - "5601:5601"
  links:
    - elasticsearch
spark:
  build: .
  dockerfile: Dockerfile.spark
  command: 0FxQbzADPEt5HQIKt7iywnzW9 ttBU5dz07D6MV7q1tOumdNR5lxHvv3YlY1bNju7L3SuWUrouiw 88786496-vo4HWJS23dG6etgnMAhimIQIPXJPO4bkAWfOGykSH aLZIP105epbmSwU4ELSUmbG5GNZGmOOmxv1L1qNoBvVCp
  ports:
    - "4040:4040"
  links:
    - elasticsearch 
